### ISSUE TITLE
Transfer to the new nREPL GitHub organization

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/drawbridge#23]
I guess we should transfer this project to https://github.com/nrepl, so it's in good company.

**Comment by bbatsov** [comment]
@cemerick Seems I can't update reply to use the new reply without updating drawbridge as well (it's a dependency of reply). Should I send you a PR here or would you prefer to do the transfer?

**Comment by cemerick** [comment]
Done!

**Comment by bbatsov** [comment]
Thanks!
